{{- $fullName := include "chart.fullname" . -}}

{{- if .Values.imagePull -}}
{{- with .Values.imagePull.credentials -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullName }}-pull-secret
data:
  .dockerconfigjson: {{ template "dockerConfig" . }}
type: kubernetes.io/dockerconfigjson
{{- end }}
{{- end }}
