{{- $fullName := include "chart.fullname" . -}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "chart.selectorLabels" . | nindent 8 }}
    spec:
      {{- if .Values.imagePull }}
      imagePullSecrets:
      {{- with .Values.imagePull.secrets }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.imagePull.credentials }}
        - name: {{ $fullName }}-pull-secret
      {{- end }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8001
              protocol: TCP
            - name: management
              containerPort: 9001
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: APP_SECURITY_ISSUER_URI
              value: "{{ .Values.security.issuerUri }}"
            - name: APP_SECURITY_PUBLIC_CLIENT_ID
              value: "{{ .Values.security.publicClientId }}"
            {{- if eq .Values.mongodb.enabled true }}
            - name: APP_MONGO_CONNECTION_URI
              value: "mongodb://{{ .Release.Name }}-mongodb:27017"
            {{- end }}
          startupProbe:
            httpGet:
              path: /health
              port: 9001
            periodSeconds: 10
            failureThreshold: 5
          livenessProbe:
            httpGet:
              path: /health/liveness
              port: 9001
            periodSeconds: 10
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /health/readiness
              port: 9001
            periodSeconds: 10
            failureThreshold: 5
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
